// LLM minutes enhancement — chunked map-reduce over the transcript. Parity port of
// src/pipeline/summarize.ts. Strictly best-effort: on generation/parse failure callers keep the
// rule-based minutes (the guaranteed floor). Takes an injected generate fn so it is testable
// without llama.
#pragma once
#include <functional>
#include <optional>
#include <string>
#include <vector>

#include "minutes/minutes_extractor.h"  // DraftMinute, MinuteUtt, MinuteSpk

namespace audionotes {

// (prompt, max_tokens) -> generated text. Wraps LlamaEngine::generate in production.
using GenerateFn = std::function<std::string(const std::string&, int)>;

std::vector<std::string> transcriptLines(const std::vector<MinuteUtt>& utterances,
                                         const std::vector<MinuteSpk>& speakers);
std::vector<std::string> chunkTranscript(const std::vector<std::string>& lines,
                                         size_t max_chars = 6000);
std::string mapPrompt(const std::string& chunk);
std::string reducePrompt(const std::string& notes);

// Narrative / summary / headline are generated by PROGRESSIVE CONDENSATION: the narrative is built
// from the notes, the summary from the narrative, the headline from the summary. Only the first
// pays a full-transcript prefill, which is the expensive part on a phone, and the three can never
// contradict each other because each is a condensation of the one above.
//
// None of them ask for JSON. Measured 2026-08-26 on the real NeoSym recording: with "summary" as a
// field inside reducePrompt's schema, Qwen2.5-1.5B answered "No decisions were explicitly stated."
// — commentary on its own extraction, contradicted by the two actions it listed beneath — while
// the same weights given summaryPrompt wrote four specific, true sentences about the meeting.
std::string narrativePrompt(const std::string& notes);
std::string summaryPrompt(const std::string& narrative);
std::string headlinePrompt(const std::string& summary);

// Merge notes into notes, same format in and out, so the result can be folded again.
std::string foldPrompt(const std::string& notes);

// Prose digests, used to build the narrative for a meeting too long to fit one prompt.
//
// The narrative is NOT built from the DECISIONS/ACTIONS/QUESTIONS notes, though it was at first.
// A 1.5B model mirrors the shape of its input: fed those notes it answered with "#### Actions:"
// and a bullet list, however firmly the prompt forbade headings. Fed dialogue or prose it writes
// prose. Since the list items now come from the rule extractor, nothing in the prose chain needs
// the notes at all — so each chunk is digested into prose and the digests are condensed.
std::string digestPrompt(const std::string& chunk);
std::string condensePrompt(const std::string& prose);

// Groups of note indices to merge so the joined notes fit max_chars. Empty when they already fit.
//
// Without this, a long meeting overruns the context: measured density on real audio is ~671
// chars/minute, so at ~14 chunks — about a two-hour meeting — the reduce prompt exceeds n_ctx,
// LlamaEngine's token guard returns an empty string, and the meeting silently ends up with no
// minutes at all.
//
// Groups always hold at least two notes: folding one note alone costs a generation and saves
// nothing. A single note that exceeds max_chars on its own is left ungrouped rather than dropped —
// the caller proceeds with an oversize prompt, which degrades output, rather than losing content.
std::vector<std::vector<int>> foldPlan(const std::vector<std::string>& notes, std::size_t max_chars);

// Returns std::nullopt when nothing parses / everything is placeholder — caller keeps the floor.
std::optional<std::vector<DraftMinute>> parseMinutesJson(const std::string& raw);

std::optional<std::vector<DraftMinute>> enhanceMinutes(const std::vector<MinuteUtt>& utterances,
                                                       const std::vector<MinuteSpk>& speakers,
                                                       const GenerateFn& generate);

// Strip markdown from generated prose: heading markers, bold/italic runs, inline code ticks, and
// any leading blank lines.
//
// The prompts forbid markdown and a 1.5B model writes "**Meeting Topic:**" and "### Summary"
// anyway — measured repeatedly on the real NeoSym recording, under several wordings. Prompt text
// reduces how often it happens and cannot make it never happen. The app renders these strings as
// plain text, so the asterisks would be shown to the reader literally.
//
// Line structure is left alone: a "- " bullet reads fine in a text block, and rewriting it would
// mean guessing at sentence boundaries.
std::string stripMarkdown(const std::string& s);

// Cut a generation back to its last complete sentence.
//
// Every prose generation runs under a token cap, and a model that ignores the length instruction
// hits it mid-word: the first summary written on a real 18-minute meeting ended "...addressed
// through direct transfers to banks which". A cap is a safety limit, not an edit, so what it
// severs must not reach the reader.
//
// A terminator only counts when the next character is whitespace or the end of the string, which
// keeps "3.5 lakh" and "e.g." from being mistaken for the end of a thought. When the text holds no
// terminator at all it is returned untouched — a long fragment still says more than nothing.
std::string trimToSentence(const std::string& s);

// Drop title and section-label lines from a prose generation.
//
// Told "no title, no heading" in five different wordings, the model still opened with "Meeting
// Summary" and then labelled each paragraph — "Meeting was about:", "What the group worked
// through:", "What was settled:" — by echoing the very topics the instruction listed. Prompt
// wording reduces how often that happens and cannot make it never happen, so the guarantee is
// made here instead.
//
// A line is a label when it is short, does not end in sentence punctuation, and either ends in a
// colon or is the first line with a blank line under it. Prose that runs to a full stop is never
// touched, and neither is a long line, so an ordinary sentence cannot be mistaken for a heading.
std::string stripLabels(const std::string& s);

// Drop a closing sentence whose content is that the meeting did NOT do something.
//
// The prompts forbid this in five wordings and the model writes it anyway, always as a final
// caveat: "...but did not conclude specific actions or decisions made". It is unhelpful at best
// and self-contradicting at worst — the Actions tab is listing items off the same meeting while
// the summary says none were reached.
//
// Only the closing sentence is examined, and only against a fixed list of the formulaic phrases
// the model actually produces, so a sentence that reports a real refusal ("the team did not want
// to change the form") is untouched. Never returns empty: if every sentence would go, the text is
// returned as it was.
std::string dropAbsenceTail(const std::string& s);

// The prose the UI leads with. Empty strings on failure; callers keep the rule-based floor.
struct Narration {
  std::string narrative;  // MOM body, three or four paragraphs
  std::string summary;    // 2-3 sentences, the Summary tab
  std::string headline;   // <= 15 words, the library row
};

// Notes characters one prompt may carry: ~4 chars/token against an 8192 context, holding back room
// for the instruction text and the answer, so foldPlan triggers before LlamaEngine's own token
// guard would fire and silently return "".
constexpr std::size_t kNotesBudgetChars = (8192 - 1600) * 4;

/**
 * map -> fold -> narrative -> summary -> headline.
 *
 * Deliberately mirrored by Narrator.kt rather than called from it: Android needs to commit each
 * chunk's note to the database as it lands and to check for cancellation between generations, and
 * neither is expressible through a single JNI call. What the two share is everything that decides
 * the OUTPUT — the prompts, the chunking and the fold plan. What differs is only checkpointing.
 * If you change the sequence here, change it there; test_llm_minutes pins the call order so the
 * drift is visible.
 */
Narration narrate(const std::vector<MinuteUtt>& utterances,
                  const std::vector<MinuteSpk>& speakers, const GenerateFn& generate,
                  std::size_t notes_budget_chars = kNotesBudgetChars);

}  // namespace audionotes
