// LLM minutes enhancement — chunked map-reduce over the transcript. Parity port of
// src/pipeline/summarize.ts. Strictly best-effort: on generation/parse failure callers keep the
// rule-based minutes (the guaranteed floor). Takes an injected generate fn so it is testable
// without llama.
#pragma once
#include <functional>
#include <optional>
#include <string>
#include <vector>

#include "minutes/minutes_extractor.h"  // DraftMinute, MinuteUtt, MinuteSpk

namespace audionotes {

// (prompt, max_tokens) -> generated text. Wraps LlamaEngine::generate in production.
using GenerateFn = std::function<std::string(const std::string&, int)>;

std::vector<std::string> transcriptLines(const std::vector<MinuteUtt>& utterances,
                                         const std::vector<MinuteSpk>& speakers);
std::vector<std::string> chunkTranscript(const std::vector<std::string>& lines,
                                         size_t max_chars = 6000);
std::string mapPrompt(const std::string& chunk);
std::string reducePrompt(const std::string& notes);

// Narrative / summary / headline are generated by PROGRESSIVE CONDENSATION: the narrative is built
// from the notes, the summary from the narrative, the headline from the summary. Only the first
// pays a full-transcript prefill, which is the expensive part on a phone, and the three can never
// contradict each other because each is a condensation of the one above.
//
// None of them ask for JSON. Measured 2026-08-26 on the real NeoSym recording: with "summary" as a
// field inside reducePrompt's schema, Qwen2.5-1.5B answered "No decisions were explicitly stated."
// — commentary on its own extraction, contradicted by the two actions it listed beneath — while
// the same weights given summaryPrompt wrote four specific, true sentences about the meeting.
std::string narrativePrompt(const std::string& notes);
std::string summaryPrompt(const std::string& narrative);
std::string headlinePrompt(const std::string& summary);

// Merge notes into notes, same format in and out, so the result can be folded again.
std::string foldPrompt(const std::string& notes);

// Groups of note indices to merge so the joined notes fit max_chars. Empty when they already fit.
//
// Without this, a long meeting overruns the context: measured density on real audio is ~671
// chars/minute, so at ~14 chunks — about a two-hour meeting — the reduce prompt exceeds n_ctx,
// LlamaEngine's token guard returns an empty string, and the meeting silently ends up with no
// minutes at all.
//
// Groups always hold at least two notes: folding one note alone costs a generation and saves
// nothing. A single note that exceeds max_chars on its own is left ungrouped rather than dropped —
// the caller proceeds with an oversize prompt, which degrades output, rather than losing content.
std::vector<std::vector<int>> foldPlan(const std::vector<std::string>& notes, std::size_t max_chars);

// Returns std::nullopt when nothing parses / everything is placeholder — caller keeps the floor.
std::optional<std::vector<DraftMinute>> parseMinutesJson(const std::string& raw);

std::optional<std::vector<DraftMinute>> enhanceMinutes(const std::vector<MinuteUtt>& utterances,
                                                       const std::vector<MinuteSpk>& speakers,
                                                       const GenerateFn& generate);

}  // namespace audionotes
